trigger:
  branches:
    include:
      - develop
      - master
  tags:
    include:
      - v1.*

resources:
  repositories:
    - repository: benk-infra
      type: git
      name: benk-infra

stages:
  - stage: BuildOnt
    displayName: Build and push develop image to ontwikkel
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/develop') )
    jobs:
      - template: templates/build_image.yaml@benk-infra
        parameters:
          environment: ont
          dockerImageName: datapunt/gob-prepare
          dockerImageTag: develop
          dockerOpts: --no-cache --target application
          srcPath: src

  - stage: BuildTst
    displayName: Build and push develop image to test
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/develop') )
    jobs:
      - template: templates/tag_image.yaml@benk-infra
        parameters:
          sourceEnvironment: ont
          destEnvironment: tst
          dockerImageName: datapunt/gob-prepare
          dockerImageTag: develop

  - stage: BuildAcc
    displayName: Build and push develop image to acceptance
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master') )
    jobs:
      - template: templates/build_image.yaml@benk-infra
        parameters:
          environment: acc
          dockerImageName: datapunt/gob-prepare
          dockerImageTag: develop
          dockerOpts: --no-cache --target application
          srcPath: src
