version: '3.4'

services:

  gobprepare:
    build:
      context: src
      target: development
    container_name: gobprepare
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      GOB_SHARED_DIR: /app/shared
      PREPARE_DATABASE_PORT_OVERRIDE: 5432
      PREPARE_DATABASE_HOST_OVERRIDE: prepare_database
      API_HOST: http://gobapi:8001
    env_file: .env
    volumes:
      - gob-volume:/app/shared
      - ./src/gobprepare:/app/gobprepare
      - ./src/tests:/app/tests
      - ${GOB_CORE_DIR-../GOB-Core}:/app/GOB-Core
      - ${GOB_CONFIG_DIR-../GOB-Config}:/app/GOB-Config

  prepare_database:
    image: amsterdam/postgres11
    ports:
      - "5408:5432"
    container_name: prepare_database
    environment:
      POSTGRES_PASSWORD: ${GOB_PREPARE_DATABASE_PASSWORD}
      POSTGRES_DB: ${GOB_PREPARE_DATABASE}
      POSTGRES_USER: ${GOB_PREPARE_DATABASE_USER}
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
    shm_size: '1gb'

volumes:
  gob-volume:
    external: true

networks:
  default:
    name: gob-network
    external: true
